version:              2.0
jobs:
  build:
    docker:
      - image:        circleci/node:9.11.1
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key:        dependency-cache-{{ checksum "package.json" }}
      - run:
          name:       Setup Dependencies
          command:    npm install
      - save_cache:   # special step to save the dependency cache
          key:        dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:          # run lint verification
          name:       Lint code
          command:    npm run lint
      - run:          #run tests
          name:       Build code
          command:    npm run build
  deploy:
    docker:
      - image:        circleci/node:9.11.1
    timeout:          1200
    environment:
      - HEROKU_APP:   wayconnect-portal
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
            key:      dependency-cache-{{ checksum "package.json" }}
      - run:
          name:       Deploy Master to Heroku
          command:    |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git master

workflows:
  version:            2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:   master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:   master
