/*
 *
 * LoaderPage constants
 *
 */

export const DEFAULT_ACTION = 'app/LoaderPage/DEFAULT_ACTION';

export const GET_ESTABLISHMENT = 'app/LoaderPage/GET_ESTABLISHMENT';
export const GET_ESTABLISHMENT_SUCCESS =
  'app/LoaderPage/GET_ESTABLISHMENT_SUCCESS';
export const GET_ESTABLISHMENT_ERROR = 'app/LoaderPage/GET_ESTABLISHMENT_ERROR';

export const POST_CONNECTION = 'app/LoaderPage/POST_CONNECTION';
export const POST_CONNECTION_SUCCESS = 'app/LoaderPage/POST_CONNECTION_SUCCESS';
export const POST_CONNECTION_ERROR = 'app/LoaderPage/POST_CONNECTION_ERROR';

export const GET_PROMOTION_LEVELS = 'app/LoaderPage/GET_PROMOTION_LEVELS';
export const GET_PROMOTION_LEVELS_SUCCESS =
  'app/LoaderPage/GET_PROMOTION_LEVELS_SUCCESS';
export const GET_PROMOTION_LEVELS_ERROR =
  'app/LoaderPage/GET_PROMOTION_LEVELS_ERROR';

export const RETRIEVE_DISCOUNT = 'app/LoaderPage/RETRIEVE_DISCOUNT';
export const RETRIEVE_DISCOUNT_SUCCESS =
  'app/LoaderPage/RETRIEVE_DISCOUNT_SUCCESS';
export const RETRIEVE_DISCOUNT_ERROR = 'app/LoaderPage/RETRIEVE_DISCOUNT_ERROR';
