// ActionTypes are defined in constants.

// They are imported in Actions and Reducers.
// This prevents errors if they are misspelled over here.

/* eslint-disable */

export const INCREMENT_NUM = "INCREMENT_NUM";
export const DECREMENT_NUM = "DECREMENT_NUM";
export const RESET = "RESET";
export const FETCH_INFORMATION = "FETCH_INFORMATION";
export const FETCH_INFORMATION_FULFILLED = "FETCH_INFORMATION_FULFILLED";
export const FETCH_INFORMATION_REJECTED = "FETCH_INFORMATION_REJECTED";
export const POST_CONNECT = "POST_CONNECT";
export const POST_CONNECT_FULFILLED = "POST_CONNECT_FULFILLED";
export const POST_CONNECT_REJECTED = "POST_CONNECT_REJECTED";

export const POST_REGISTER_FORM = "POST_REGISTER_FORM";
export const POST_REGISTER_FORM_FULFILLED = "POST_REGISTER_FORM_FULFILLED";
export const POST_REGISTER_FORM_REJECTED = "POST_REGISTER_FORM_REJECTED";
export const POST_CLAIM = "POST_CLAIM";
export const POST_CLAIM_FULFILLED = "POST_CLAIM_FULFILLED";
export const POST_CLAIM_REJECTED = "POST_CLAIM_REJECTED";
export const FETCH_FIDELITY = "FETCH_FIDELITY";
export const FETCH_FIDELITY_FULFILLED = "FETCH_FIDELITY_FULFILLED";
export const FETCH_FIDELITY_REJECTED = "FETCH_FIDELITY_REJECTED";
export const FETCH_DISCOUNT = "FETCH_DISCOUNT";
export const FETCH_DISCOUNT_FULFILLED = "FETCH_DISCOUNT_FULFILLED";
export const FETCH_DISCOUNT_REJECTED = "FETCH_DISCOUNT_REJECTED";

/* eslint-enable */
