/*
 *
 * Journey constants
 *
 */

export const DEFAULT_ACTION = 'app/Journey/DEFAULT_ACTION';

export const JOURNEY_ID_CHANGED = 'app/Journey/JOURNEY_ID_CHANGED';

export const CURRENT_JOURNEY_ITEM_CHANGED =
  'app/Journey/CURRENT_JOURNEY_ITEM_CHANGED';
export const CURRENT_JOURNEY_ITEM_INCREMENTED =
  'app/Journey/CURRENT_JOURNEY_ITEM_INCREMENTED';

export const CHANGE_DEFAULT_ANSWERS_LIST =
  'app/Journey/CHANGE_DEFAULT_ANSWERS_LIST';

export const ACKNOWLEDGE_COMMUNICATION =
  'app/Journey/ACKNOWLEDGE_COMMUNICATION';
export const ACKNOWLEDGE_COMMUNICATION_SUCCESS =
  'app/Journey/ACKNOWLEDGE_COMMUNICATION_SUCCESS';
export const ACKNOWLEDGE_COMMUNICATION_ERROR =
  'app/Journey/ACKNOWLEDGE_COMMUNICATION_ERROR';

export const SKIP_VIDEO = 'app/Journey/SKIP_VIDEO';
export const SKIP_VIDEO_SUCCESS = 'app/Journey/SKIP_VIDEO_SUCCESS';
export const SKIP_VIDEO_ERROR = 'app/Journey/SKIP_VIDEO_ERROR';

export const COMPLETE_JOURNEY = 'app/Journey/COMPLETE_JOURNEY';
export const COMPLETE_JOURNEY_SUCCESS = 'app/Journey/COMPLETE_JOURNEY_SUCCESS';
export const COMPLETE_JOURNEY_ERROR = 'app/Journey/COMPLETE_JOURNEY_ERROR';

export const AUTHENTICATE = 'app/Journey/AUTHENTICATE';
export const AUTHENTICATE_SUCCESS = 'app/Journey/AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_ERROR = 'app/Journey/AUTHENTICATE_ERROR';

export const ANSWER_QUESTION = 'app/Journey/ANSWER_QUESTION';
export const ANSWER_QUESTION_SUCCESS = 'app/Journey/ANSWER_QUESTION_SUCCESS';
export const ANSWER_QUESTION_ERROR = 'app/Journey/ANSWER_QUESTION_ERROR';
