/*
 *
 * Journey constants
 *
 */

export const DEFAULT_ACTION = 'app/Journey/DEFAULT_ACTION';

export const ACKNOWLEDGE_COMMUNICATION =
  'app/Journey/ACKNOWLEDGE_COMMUNICATION';
export const ACKNOWLEDGE_COMMUNICATION_SUCCESS =
  'app/Journey/ACKNOWLEDGE_COMMUNICATION_SUCCESS';
export const ACKNOWLEDGE_COMMUNICATION_ERROR =
  'app/Journey/ACKNOWLEDGE_COMMUNICATION_ERROR';

export const SKIP_VIDEO = 'app/Journey/SKIP_VIDEO';
export const SKIP_VIDEO_SUCCESS = 'app/Journey/SKIP_VIDEO_SUCCESS';
export const SKIP_VIDEO_ERROR = 'app/Journey/SKIP_VIDEO_ERROR';

export const AUTHENTICATE = 'app/Journey/AUTHENTICATE';
export const AUTHENTICATE_SUCCESS = 'app/Journey/AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_ERROR = 'app/Journey/AUTHENTICATE_ERROR';

export const JOURNEY_ID_INCREASED = 'app/Journey/JOURNEY_ID_INCREASED';
export const JOURNEY_ID_DECREASED = 'app/Journey/JOURNEY_ID_DECREASED';
export const JOURNEY_ID_OUTOFRANGE = 'app/Journey/JOURNEY_ID_OUTOFRANGE';

export const ANSWER_QUESTION = 'app/Journey/ANSWER_QUESTION';
export const ANSWER_QUESTION_SUCCESS = 'app/Journey/ANSWER_QUESTION_SUCCESS';
export const ANSWER_QUESTION_ERROR = 'app/Journey/ANSWER_QUESTION_ERROR';
